160: Migrate to ResourceLoader
openedx/xblock-qualtrics-survey pull request #165
Opened 2024-09-16 10:40 UTC by abdullahQureshee

# Overview
Resolves https://github.com/openedx/xblock-qualtrics-survey/issues/160

# Test Instructions
- Checkout the branch
- make test

# TODO
- [x] Lint all files
- [x] Pass all tests
- [x] Bump the version number in `setup.py`
- [x] Attach screenshots?

# Screenshots

## cms
<img width="1198" alt="Screenshot 2024-09-16 at 3 38 52 PM" src="https://github.com/user-attachments/assets/6d033880-3f5e-4ea2-9ce4-b08868dc4ba5">

## lms
<img width="981" alt="Screenshot 2024-09-16 at 3 39 48 PM" src="https://github.com/user-attachments/assets/137f572a-d8ec-4db5-84e9-0c987af02efa">

2024-09-16 12:00 UTC, farhan commented
Update the major version to release this xblock

2024-09-23 10:42 UTC, farhan requested changes

2024-09-23 10:42 UTC, farhan commented on tox.ini
> +envlist = csslint,eslint,py311-django{42},py312-django{42},quality
Update to
```yml
csslint,eslint,py{311,312}-django{42},quality
```

2024-09-23 10:42 UTC, farhan commented on setup.py
> +version = '1.5.1'
Update major version as we are dropping support of Python 3.8

2024-09-30 13:17 UTC, farhan commented on setup.py
> +version = '1.5.1'
Please update it to 2.0.0

2024-10-03 07:06 UTC, farhan approved these changes

2024-10-25 16:29 UTC, feanil approved these changes

2024-10-25 16:30 UTC, merged